services:
  api:
    path: resources/api
  single-lambda-ddb:
    path: resources/dynamodb/single-lambda-ddb
  single-lambda:
    params:
      API_GATEWAY_REST_API_ID: ${api.ApiId}
      API_GATEWAY_REST_API_ROOT_RESOURCE_ID: ${api.ApiResourceId}
      DYNAMODB_TABLE_SINGLE-LAMBDA-DDB: ${single-lambda-ddb.DynamoDBTableName}
    path: services/single-lambda
